JoSaTech/JoSaTech/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from orders import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


JoSaTech/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^$', views.Index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^orderbook/$', views.OrderBook, name='orderbook'),
    url(r'^dealjournal/$', views.DealJournal, name='dealjournal'),
    url(r'^add_order/$', views.add_order, name='add_order'),
    url(r'^(?P<order_id>[0-9]+)/delete_order/$', views.delete_order, name='delete_order'),
    url(r'^(?P<trade_id>[0-9]+)/delete_trade/$', views.delete_trade, name='delete_trade'),
    url(r'^exchange/$', views.exchange, name='exchange'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^delete_all/$', views.delete_all, name='delete_all'),
    url(r'^randomize/$', views.randomize, name='randomize')
]

JoSaTech/orders/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Order(models.Model):
    order_id = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, default=1)
    fund_name = models.CharField(max_length=250)
    share_name = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(max_length=8, validators=[MinValueValidator(1), MaxValueValidator(500000)])
    price = models.FloatField(max_length=8, validators=[MinValueValidator(0.1)])
    total_order = models.FloatField(max_length=8)
    buysell = models.CharField(max_length=4)
    timestamp = models.DateTimeField(auto_now_add=True)
    filled = models.IntegerField(max_length=8, default=0)

    def __str__(self):
        return str(self.id) + ' - ' + self.fund_name + ' - ' + self.share_name + ' - ' + str(self.total_order)

class Trade(models.Model):
    trade_id = models.PositiveIntegerField(default=0)
    share_name = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(max_length=8, validators=[MinValueValidator(1)])
    price = models.FloatField(max_length=8, validators=[MinValueValidator(0.1)])
    total_order = models.FloatField(max_length=8)
    selling_fund = models.CharField(max_length=250)
    buying_fund = models.CharField(max_length=250)
    selling_orderID = models.CharField(max_length=10)
    buying_orderID = models.CharField(max_length=10)
    index = models.FloatField(max_length=8)

    def __str__(self):
        return str(self.id) + ' - ' + self.share_name + ' - ' + str(self.total_order)

class Price(models.Model):
    share_name = models.CharField(max_length=100)
    close_price = models.FloatField(max_length=8)

    def __str__(self):
        return self.share_name + ' - ' + str(self.close_price)

JoSaTech/orders/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order, Price

Shares = Price.objects.values_list('share_name', flat=True)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['share_name', 'quantity', 'price']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        s = [(x,x) for x in Shares]
        self.fields['share_name'].widget = forms.Select(choices=s)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']




JoSaTech/orders/views.py
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Permission, User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect
from .models import Order, Trade, Price
from random import choice, randint
from datetime import datetime
from .forms import OrderForm, UserForm
from collections import defaultdict, OrderedDict
#import schedule
import time
from graphos.sources.model import ModelDataSource
from graphos.renderers.gchart import LineChart
from django.contrib import messages


Shares = Price.objects.values_list('share_name', flat=True)
ClosePrices = Price.objects.values_list('close_price', flat=True)
Funds = ['JRAM','Fundlicious','Sanguard','HotnFund','Fundrama','RoboFund']
StartValue = 100000
diversification_threshold = 5 #percent per share
diversification_bonus = 10000
random_market = False

def Random_Ross():
    orderIDs = Order.objects.values_list('order_id', flat=True)
    order_id = orderIDs.last() + 1
    #fund_name = 'Market'
    fund_name = choice(Funds)
    r = randint(1, Shares.count())
    share_name = Shares[r-1]
    r2 = randint(-15, 20)
    quantity = 100+(5*r2)
    price = round(ClosePrices[r - 1] * (1 + r2 / 100),2)
    total_order = round(price * quantity, 2)
    choices = ['Buy','Sell']
    buysell = choice(choices)
    timestamp = str(datetime.now())
    filled = 0
    Order.objects.create(order_id= order_id, fund_name=fund_name, share_name=share_name, quantity=quantity, price=price,
                         total_order=total_order, buysell=buysell, timestamp=timestamp, filled=filled)


def ShareMatch():
    for sharenum in Shares:
       match = True
       while match == True:
           #create sublists of Buy orders and Sell orders (separately) per share assuming it has not been fully filled
           BuyOrdersToBeSorted = []
           SellOrdersToBeSorted = []
           for sublist in Order.objects.filter(share_name=sharenum):
               if (sublist.buysell == 'Buy') and (sublist.quantity-sublist.filled > 0):
                   BuyOrdersToBeSorted.append(sublist)
               if (sublist.buysell == 'Sell') and (sublist.quantity-sublist.filled > 0):
                   SellOrdersToBeSorted.append(sublist)
           #sort sublist to get highest Buy order and lowest Sell order
           SortedBuyOrders = sorted(BuyOrdersToBeSorted, key=lambda x: x.price, reverse=True)
           SortedSellOrders = sorted(SellOrdersToBeSorted, key=lambda x: x.price)
           if not SortedBuyOrders or not SortedSellOrders:
               match = False
           else:
           #elif (SortedBuyOrders[0].fund_name != SortedSellOrders[0].fund_name) or (SortedBuyOrders[0].fund_name == 'Market'):
               HighestBuyOrder = SortedBuyOrders[0]
               LowestSellOrder = SortedSellOrders[0]
               #determine how many shares matched and update DealJournal accordingly
               if HighestBuyOrder.price >= LowestSellOrder.price: #and ((HighestBuyOrder[0] != LowestSellOrder[0]) or (HighestBuyOrder[0] == 'Market')): this doesn't work because it will never fund the next highest buy order or lowest sell order
                   match = True
                   MatchingShares = min(HighestBuyOrder.quantity - HighestBuyOrder.filled,LowestSellOrder.quantity - LowestSellOrder.filled)
                   HighestBuyOrder.filled = HighestBuyOrder.filled + MatchingShares
                   LowestSellOrder.filled = LowestSellOrder.filled + MatchingShares
                   #Insert amended highest buy order and lowest sell order back into Order table
                   hbo = Order.objects.get(id=HighestBuyOrder.id)
                   hbo.filled = HighestBuyOrder.filled
                   hbo.save()
                   lso = Order.objects.get(id=LowestSellOrder.id)
                   lso.filled = LowestSellOrder.filled
                   lso.save()
                   index = 0
                   #update ClosePrice
                   cp = Price.objects.get(share_name=HighestBuyOrder.share_name)
                   cp.close_price = LowestSellOrder.price
                   cp.save()
                   ClosePrices = Price.objects.values_list('close_price', flat=True)
                   for sum in range(len(ClosePrices)):
                       index += ClosePrices[sum]
                   tradeIDs = Trade.objects.values_list('trade_id', flat=True)
                   if tradeIDs:
                       trade_id = tradeIDs.last() + 1
                   else:
                       trade_id = 1
                   # create new dealjournal entry
                   Trade.objects.create(share_name=HighestBuyOrder.share_name, quantity=MatchingShares,
                                        price=LowestSellOrder.price, trade_id=trade_id,
                                        total_order=round(MatchingShares * LowestSellOrder.price, 2),
                                        buying_fund=HighestBuyOrder.fund_name,
                                        selling_fund=LowestSellOrder.fund_name, buying_orderID=HighestBuyOrder.id,
                                        selling_orderID=LowestSellOrder.id, index=index)
               else:
                   match = False
           #else:
           #    match = False

def portfolio_create(request):
    fundr = str(request.user)
    all_trades = Trade.objects.all()
    all_funds = Order.objects.values_list('fund_name', flat=True).distinct()
    portfoliodict = {}
    sharedict = {}
    for fund in all_funds:
        # if fund == fundr:
            pos = 0
            penalty = 0
            totalsharevalue = 0
            overdraft = 0
            margin = 0
            portfoliodict[fund] = {}
            sharedict[fund] = {}
            for share in Shares:
                buytrades = 0
                selltrades = 0
                buyprice = 0
                sellprice = 0
                buyquantity = 0
                sellquantity = 0
                for trade in all_trades:
                    if fund == trade.selling_fund:
                        selltrades += trade.total_order
                        if share == trade.share_name:
                            sellquantity += trade.quantity
                            sellprice += trade.total_order
                    if fund == trade.buying_fund:
                        buytrades += trade.total_order
                        if share == trade.share_name:
                            buyquantity += trade.quantity
                            buyprice += trade.total_order

                if buyquantity != 0:
                    avgbuyprice = buyprice / buyquantity
                else:
                    avgbuyprice = '-'
                if sellquantity != 0:
                    avgsellprice = sellprice / sellquantity
                else:
                    avgsellprice = '-'
                #test = sharedict[fund].value
                totalquantity = buyquantity - sellquantity
                cp = Price.objects.filter(share_name=share)[0]
                sharevalue = totalquantity * cp.close_price
                totalsharevalue += sharevalue
                if sharevalue < 0:
                    margin += abs(sharevalue)
                share_dict ={'buys': buyquantity,'sells': sellquantity, 'quantity': totalquantity, 'value': sharevalue,
                             'avgbuyprice': avgbuyprice, 'avgsellprice': avgsellprice, 'closeprice': cp.close_price}
                sharedict[fund].update({share: share_dict})
                pos += 1

            margin = margin / 2
            margininterest = margin * 0.04
            closecash = StartValue + selltrades - buytrades - margin
            if closecash < 0:
                overdraft += abs(closecash) * 0.10
            elif closecash > 10000:
                penalty += (closecash - 10000) * 0.05

            cashplusshares = closecash + totalsharevalue
            cashpercent = closecash / cashplusshares * 100
            sharepercent = totalsharevalue / cashplusshares * 100
            check = 0
            for share in Shares:
                sharedict[fund][share].update({'percent': sharedict[fund][share].get('value')/cashplusshares*100})
                if (sharedict[fund][share].get('value')/cashplusshares*100) >= diversification_threshold:
                    check += 1
            if check == Shares.count():
                divbonus = diversification_bonus
            else:
                divbonus = 0
            portfoliovalue = closecash + totalsharevalue - penalty - overdraft + divbonus - margininterest + margin
            portfoliogrowth = (portfoliovalue - StartValue) / StartValue * 100


            portfoliodict[fund].update({'portfoliovalue': portfoliovalue, 'portfoliogrowth': portfoliogrowth,
                                        'selltrades': selltrades, 'buytrades': buytrades, 'closecash': closecash,
                                        'sharevalue': totalsharevalue, 'penalty': penalty, 'cashpercent': cashpercent,
                                        'sharepercent': sharepercent, 'divbonus': divbonus, 'margin': margin,
                                        'margininterest': margininterest, 'overdraft': overdraft, 'sharedeets': sharedict[fund]})
            portfoliodict = OrderedDict(sorted(portfoliodict.items(), key=lambda x: x[1]['portfoliovalue'], reverse=True))
    return portfoliodict


def add_order(request):
    global random_market
    orderIDs = Order.objects.values_list('order_id', flat=True)
    if orderIDs:
        order_id = orderIDs.last() + 1
    else:
        order_id = 1
    fundr = str(request.user)

JoSaTech/orders/templates/orders/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}JoSa Technologies{% endblock %}</title>
    {% load static %}
    {% load humanize %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'orders/style.css' %}" />
    <script src="https://fonts.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'orders/main.js' %}"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
    </script>
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'orders:index' %}">JoSa Technologies</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                 <li class="{% block orderadd_active %}{% endblock %}">
                    <a href="{% url 'orders:add_order' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Order
                    </a>
                </li>
                <li class="{% block exchange_active %}{% endblock %}">
                    <a href="{% url 'orders:exchange' %}">
                        <span class="glyphicon glyphicon-random" aria-hidden="true"></span>&nbsp; Exchange
                    </a>
                </li>
                <li class="{% block portfolio_active %}{% endblock %}">
                    <a href="{% url 'orders:portfolio' %}">
                        <span class="glyphicon glyphicon-euro" aria-hidden="true"></span>&nbsp; Portfolio
                    </a>
                </li>
                {% if fundr == 'Market' %}
                <li class="{% block orderbook_active %}{% endblock %}">
                    <a href="{% url 'orders:orderbook' %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Orderbook
                    </a>
                </li>
                <li class="{% block dealjournal_active %}{% endblock %}">
                    <a href="{% url 'orders:dealjournal' %}">
                        <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>&nbsp; Dealjournal
                    </a>
                </li>
                <li class="{% block randomize_active %}{% endblock %}">
                    <a href="{% url 'orders:randomize' %}">
                        <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>&nbsp; Randomize
                    </a>
                </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'orders:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

JoSaTech/orders/templates/orders/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}JoSa Technologies{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'orders/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'orders/main.js' %}"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
    </script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'orders:index' %}">JoSa Technologies</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'orders:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'orders:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

JoSaTech/orders/templates/orders/dealjournal.html
{% extends 'orders/base.html' %}
{% block title %}Dealjournal{% endblock %}
{% block dealjournal_active %}active{% endblock %}

{% block body %}

<h1>Deal Journal</h1>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Trade ID</th>
                            <th>Share Name</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total Order</th>
                            <th>Buying Fund</th>
                            <th>Order ID</th>
                            <th>Selling Fund</th>
                            <th>Order ID</th>
                            <th>Index</th>
                            <th>Delete Trade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for trade in all_trades|dictsortreversed:'id' %}
                            <tr>
                                <td>{{ trade.trade_id }}</td>
                                <td>{{ trade.share_name }}</td>
                                <td>{{ trade.quantity }}</td>
                                <td>{{ trade.price }}</td>
                                <td>{{ trade.total_order }}</td>
                                <td>{{ trade.buying_fund }}</td>
                                <td>{{ trade.buying_orderID }}</td>
                                <td>{{ trade.selling_fund }}</td>
                                <td>{{ trade.selling_orderID }}</td>
                                <td>{{ trade.index|floatformat:2 }}</td>
                                <td>
                                    <form action="{% url 'orders:delete_trade' trade.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="trade_id" value="{{ trade.id }}" />
                                        <button type="submit" name="delete" value=1 class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

JoSaTech/orders/templates/orders/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

JoSaTech/orders/templates/orders/login.html
{% extends 'orders/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'orders:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Fund name:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'orders:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

JoSaTech/orders/templates/orders/orderbook.html
{% extends 'orders/base.html' %}
{% block title %}Order book{% endblock %}
{% block orderbook_active %}active{% endblock %}

{% block body %}

<h1>Order Book</h1>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Order ID</th>
                            <th>Fund</th>
                            <th>Share Name</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total Order</th>
                            <th>Buy/Sell</th>
                            <th>Filled Shares</th>
                            <th>Timestamp</th>
                            <th>Cancel Order</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in all_orders|dictsortreversed:'id' %}
                            <tr>
                                <td>{{ order.order_id }}</td>
                                <td>{{ order.fund_name }}</td>
                                <td>{{ order.share_name }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>{{ order.price }}</td>
                                <td>{{ order.total_order }}</td>
                                <td>{{ order.buysell }}</td>
                                <td>{{ order.filled }}</td>
                                <td>{{ order.timestamp }}</td>
                                <td>
                                    <form action="{% url 'orders:delete_order' order.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="order_id" value="{{ order.id }}" />
                                        <button type="submit" name="delete" value=1 class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-remove"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

JoSaTech/orders/templates/orders/randomize.html
{% extends 'orders/base.html' %}
{% block title %}Randomize{% endblock %}
{% block randomize_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-2">
        <h2>Randomize</h2>
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" name="start" value=1 class="btn btn-success">Start</button>&nbsp&nbsp
                                <button type="submit" name="stop" value=1 class="btn btn-danger">Stop</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

JoSaTech/orders/templates/orders/register.html
{% extends 'orders/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'orders/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'orders:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}